### ISSUE TITLE
Where is Filerun?

### ISSUE THREAD

**Issue by gabrielwhite** [henryouly/filerun-alpine#1]
Hi!

I was reading through the docker-compose.yaml, and I only saw reference to php-fm, nginx and mariadb. Where's FileRun?

Thanks,

Gabe

**Comment by henryouly** [comment]
FileRun is part of a custom built nginx package.

See https://github.com/henryouly/filerun-alpine/blob/master/nginx/Dockerfile

**Comment by gabrielwhite** [comment]
Maybe I asked the wrong question. 

The docker-compose only refers to other dockers and not to yours. If I run your docker-compose file on my computer I don’t end up with any filerun packages running. 

How do I get this up and running on my own system?

Thanks!

**Comment by gabrielwhite** [comment]
I’m confused about how this relates to the images on Docker Hub.

**Comment by henryouly** [comment]
The docker-compose.yaml file used in this repo is for building a local docker image (I'm using that for my actual setup.)

If you'd like to use the prebuilt docker images on Docker Hub, you can replace this 
```
  nginx:
    build:
      context: nginx
```
with
```
  nginx:
    image: henryouly/filerun-alpine
```

similarly, replace php section with
```
  php:
    image: henryouly/filerun-alpine-php-fpm
```

I do not have an active instance to test it right now. If you run into any problems please paste the output of `docker-compose up -d`.
